### ISSUE TITLE
DS918+ request

### ISSUE THREAD

**Issue by lordvalium** [OKit-Scripts-Projects/DSM.Customizations#1]
Hi, 
i have a DS918+ with appollolake architecture. 
This is an amazing Great project and i would like to use and participate. 

Could it be possible to write how to install on a factory default DS918 and pre-compile it please?

Thank you very much.

**Comment by tenhow** [comment]
I would compile it for you, if success, then I will write down how to compile one.

**Comment by tenhow** [comment]
@lordvalium [tenhow.debian-chroot.dsm6.[1/2].apollolake](https://www.dropbox.com/s/aef5a6a70tparbc/tenhow.debian-chroot.dsm6.%5B1%3A2%5D.apollolake.zip?dl=0) 

You can download and try, as I don't have DS918+.
 And then please report result here, whether it works.

**Comment by tenhow** [comment]
this will always not work. I mentioned, this WebUI will not work.

**Comment by tenhow** [comment]
I have not figure out why the WebUI not work, maybe someone has solutions.
As I don't need to use it, too simple, little function.
You should just use ssh.
[Instructions](https://github.com/OKit-Scripts-Projects/DSM.Customizations/blob/master/App.Debian-Chroot.md)

**Comment by lordvalium** [comment]
Wow! @tenhow  that was a really great job. Seems that everything is working. Would you show me how you compiled it for my architecture? That i could support in future?

**Comment by tenhow** [comment]
@lordvalium [Compile Guide](https://github.com/OKit-Scripts-Projects/DSM.Customizations/blob/master/How.to.compile.spk.md)

**Comment by lordvalium** [comment]
> @lordvalium
> Here is a step-by-step guide for you.
> [How to _**compile**_ spk _**step-by-step**_ Guide](https://github.com/OKit-Scripts-Projects/DSM.Customizations/blob/master/How.to.compile.spk.md#How.to.compile.spk)

Thank you. I will download docker and give it a try :)

**Comment by Tao87-04** [comment]
Possible, that you compile a Version for DS1213+cedarview (x64) Arch?

**Comment by tenhow** [comment]
@Tao87-04 
That's Ok.

**Comment by tenhow** [comment]
@Tao87-04 
Now, you can download here.
[Debian-Chroot](https://github.com/OKit-Scripts-Projects/DSM.Customizations/blob/master/App.Debian-Chroot.md#Instructions)

**Comment by tenhow** [comment]
And then please report result here, whatever it works.

**Comment by tenhow** [comment]
The package for you has been uploaded, and you can download it via the links below.

[Debian-Chroot.Instructions](https://github.com/OKit-Scripts-Projects/DSM.Customizations/blob/master/App.Debian-Chroot.md#Instructions), and [Download Links](https://github.com/OKit-Scripts-Projects/DSM.Customizations/blob/master/App.Debian-Chroot.md#Instructions) is followed the instructions.

Please read that instructions carefully, it will show you how to use this spk.

Please read that instructions carefully, it will show you how to use this spk.

Please read that instructions carefully, it will show you how to use this spk.

And then please report result here, whatever it works.

If it not work, we will discuss here.

And if it helps, just give it a star.

Happy hacking!

**Comment by Tao87-04** [comment]
Hello, Big Thanky for your Support. Debian Chroot package dont change status on packagecenter, i presses run serveral times. Console say same  " /var/packages/debian-chroot/scripts/start-stop-status status
Debian Chroot is not running
" So i start via Console, it starts. After that i want update it, but it fails

root@DS2413:/# apt-get update
apt-get: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory. 

so i tryd to install it 

root@DS2413:/# apt-get install libstdc++.so.6
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?

**Comment by tenhow** [comment]
...good

**Comment by Tao87-04** [comment]
Maybe you can add a line to your instructions , thats after install the chroot, a Reboot necessary is?

**Comment by droidboxma** [comment]
Hey, is it possible to compile a version for DS1817+ (amd64) with INTEL Atom C2538.
I run DSM 6.2.1-23824 Update 1

Thx droidbox

**Comment by tenhow** [comment]
> after install the chroot, a Reboot

I have not meet this problem, but I would add it.

**Comment by tenhow** [comment]
@droidboxma, please add a new issue. I will close this.

**Comment by tenhow** [comment]
@droidboxma done. U can download and test now.

**Comment by droidboxma** [comment]
Thanks it run. Is it possible to update the chroot to Stretch?

**Comment by tenhow** [comment]
Maybe possible, but a lot of work to do.

**Comment by christofkac** [comment]
In case you still monitor this thread: Can the version for the 918+ also be used for the 218+?
If not, can it be "simply" created?
Thanks!

**Comment by tenhow** [comment]
OK, I wish to do, but my compile envirenment is down. Sorry about this, if you would like to compile one by yourself, you can follow my instruction. and it's not quiet difficult. https://github.com/OKit-Scripts-Projects/DSM.Customizations/blob/master/How.to.compile.spk.md#Brief


 





------------------ 原始邮件 ------------------
发件人: "christofkac"<notifications@github.com>;
发送时间: 2019年8月4日(星期天) 上午6:12
收件人: "OKit-Scripts-Projects/DSM.Customizations"<DSM.Customizations@noreply.github.com>;
抄送: "Tang Hao Tsui"<273481701@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [OKit-Scripts-Projects/DSM.Customizations] DS918+ request (#1)




In case you still monitor this thread: Can the version for the 918+ also be used for the 218+?
 If not, can it be "simply" created?
 Thanks!

**Comment by m3eu** [comment]
Hi Tenhow, I hope your compile environment is up and running again. Would it be possible to request a compile for the 214+ ARM architecture? TIA
