### ISSUE TITLE
DS213+ Request

### ISSUE THREAD

**Issue by Yagz** [OKit-Scripts-Projects/DSM.Customizations#10]
Hi,

Is it possible to compile this for a Synology  DS213+ with Qoriq architecture ?

Thank you very much.

**Comment by tenhow** [comment]
Sure,I found that arch.

**Comment by tenhow** [comment]
https://www.dropbox.com/s/t328ef3hyuhe9ko/debian-chroot_qoriq-_8.4-7.spk?dl=0

**Comment by tenhow** [comment]
here you are.

**Comment by Yagz** [comment]
Thank you very much.

**Comment by tenhow** [comment]
You are welcome.
