### ISSUE TITLE
DS918+ need python only

### ISSUE THREAD

**Issue by Speedmod88** [OKit-Scripts-Projects/DSM.Customizations#11]
Hi, I try to install your 918+ version on my dsm but there no Python available on the apps store to let me install debian chroot... can you compile me a python.spk that suit for the new DSM update for 918+

Thank you

**Comment by tenhow** [comment]
OK, I'll compile python for 918+ later.

**Comment by tenhow** [comment]
Compiling...

**Comment by tenhow** [comment]
Here you are. 
https://www.dropbox.com/s/drbhxrvy2cvdd8c/python_apollolake-_2.7.14-19.spk.zip?dl=0

**Comment by tenhow** [comment]
Sorry,I've compiled one for alphine.

**Comment by tenhow** [comment]
recompile

**Comment by tenhow** [comment]
Here you are.
https://www.dropbox.com/s/drbhxrvy2cvdd8c/python_apollolake-_2.7.14-19.spk.zip?dl=0

**Comment by tenhow** [comment]
I find that link may does not work, cause MacOS may do something extra, and if you are using windows or linux, it is ok. Whatever, I reuploaded a tested one
https://www.dropbox.com/s/m6hvsjs0mucmigx/python_apollolake-_2.7.14-19.spk?dl=0

**Comment by tenhow** [comment]
![屏幕快照 2019-05-06 下午10 37 25](https://user-images.githubusercontent.com/8122371/57233236-d5501280-7050-11e9-9eeb-0f3b400ef25e.jpg)

![屏幕快照 2019-05-06 下午10 40 49](https://user-images.githubusercontent.com/8122371/57233249-daad5d00-7050-11e9-86d1-7f457fb46ade.jpg)

I tested on my DS918+, as you can see, it works!

**Comment by Speedmod88** [comment]
awesome thanks
I’ll install it soon to test it
atm I’m using the virtual management

thank you for all your works
Best Regards

**Comment by tenhow** [comment]
If it shows stopped, don't be worry. It is running well ,Because of some code about interface,just shows stopped. And I would not spend time on it.
try this command in ssh, you will find out you can enter chroot debian.
chroot "/volume1/@appstore/debian-chroot/var/chroottarget" "/bin/bash" #

**Comment by tenhow** [comment]
virtual management is virtual, after all. Chroot is much better, lower resource usage, better performance.

**Comment by Speedmod88** [comment]
yes Debian chroot use lower ressource that’s why I want to use it xD

so to enter ssh of the debian chroot, I need to use that cmd first in my dsm ssh??

**Comment by tenhow** [comment]
no, if you have already configured sshd in debian chroot, you do not need to do this.
this is the command for entering debian chroot from dsm ssh.

**Comment by tenhow** [comment]
if there's nothing wrong, I would like to close this issue.
