### ISSUE TITLE
DS119j - Request

### ISSUE THREAD

**Issue by crospa91** [OKit-Scripts-Projects/DSM.Customizations#12]
Hello, is it possibile to have it compiled for the armada37xx on the Synology DS119J?

Many Thanks

**Comment by tenhow** [comment]
Sorry, synology just releases those kernels for armada, as there is no armada37xx.
syno-armada370-4.3
syno-armada370-5.0
syno-armada370-5.1
syno-armada370-5.2
syno-armada370-6.1
syno-armada375-5.1
syno-armada375-5.2
syno-armada375-6.1
syno-armada38x-5.2
syno-armada38x-6.1
syno-armadaxp-4.3
syno-armadaxp-5.0
syno-armadaxp-5.1
syno-armadaxp-5.2
syno-armadaxp-6.1
