### ISSUE TITLE
Packages for DS715 (Alpine)

### ISSUE THREAD

**Issue by schumi2004** [OKit-Scripts-Projects/DSM.Customizations#13]
Would it be possible to create packages for my Synology DS715 (Alpine)?

Thanks in advance.

**Comment by tenhow** [comment]
sure, I'll do it later

**Comment by tenhow** [comment]
Some errors happen

**Comment by tenhow** [comment]
You can compile it yourself following my manual,or a long time later for my compiling.

**Comment by schumi2004** [comment]
Great, thanks.

**Comment by tenhow** [comment]
Sorry for it, but I do not known where the error is, and I will set up a atomatic compiling flow some days later. And recompile them. If you do not want to wait, you can follow the guide I wrote.

**Comment by schumi2004** [comment]
Did not had any success yet with compiling it but it was a long time ago i tried. I did not see any download either so i think you did not made any progress also?
