### ISSUE TITLE
Package DS215j update

### ISSUE THREAD

**Issue by destoron** [OKit-Scripts-Projects/DSM.Customizations#14]
Hi, 
your package for DS215j doesn't work with DSM 6.2.1-23824 Update 6. I build with your manual a new one:

https://www.dropbox.com/s/1oahcid1ctf718z/debian-chroot_armada375-_8.4-7.spk

Thanks for all.

**Comment by tenhow** [comment]
Thanks, is there any thing need to be modified for DSM6.2.1 different with DSM6.2?
Cause I am using DSM6.2.

**Comment by tenhow** [comment]
I would like to compile a batch of spks for all the platform according your information. Lol

**Comment by destoron** [comment]
Nothing special, easy job.

**Comment by tenhow** [comment]
Could you please give me the hint, like the path changes?I'll add it to the manual.

**Comment by tenhow** [comment]
I'm wondering where is the differences.

**Comment by tenhow** [comment]
Seems  Tool Chains updated to 6.2

**Comment by tenhow** [comment]
@destoron as you mentioned above, I don't have a DS215j. So I installed on a DS918+ with same DSM 6.2.1-23824 Update 6,  and it works fine. I have not meet your problem.Is there any detailed information?

**Comment by tenhow** [comment]
![屏幕快照 2019-05-06 下午10 37 25](https://user-images.githubusercontent.com/8122371/57232786-f2381600-704f-11e9-80f0-a8d1fe166da4.jpg)

![屏幕快照 2019-05-06 下午10 40 49](https://user-images.githubusercontent.com/8122371/57232820-0714a980-7050-11e9-8ef0-7ff0af96e710.jpg)

As you can see, it works fine on my machine. Would you like to tell me what you have met and where do you modified?

**Comment by destoron** [comment]
I will check it later. I think the message was, that the package isn't for my DSM Version.

**Comment by tenhow** [comment]
Maybe I put another platform's pkg to it? Cause I compiled them by hands,not automatic.Sorry.

**Comment by tenhow** [comment]
Or Maybe I compiled a 5.x

**Comment by tenhow** [comment]
But on DSM 6.2.1 UPDATE 6.I really meet something, the web interface shows stopped, but debian-chroot is running well.

**Comment by tenhow** [comment]
if there's nothing wrong, I would close this issue.
