### ISSUE TITLE
synology 6.2.2 debian chroot

### ISSUE THREAD

**Issue by thefirstbreath** [OKit-Scripts-Projects/DSM.Customizations#15]
Hi,

will there be an updatet version?

Thanks in advance

andi

**Comment by tenhow** [comment]
Is this package work for 6.2.2?

**Comment by tenhow** [comment]
You Can try cause it will not harm your device

**Comment by tenhow** [comment]
Maybe they are still using the same kernel, as I don't have a 6.2.2 system. So you can try to install it and make a test.

**Comment by tenhow** [comment]
I'll close this issue if there is no feedback.
