### ISSUE TITLE
DS212 request

### ISSUE THREAD

**Issue by balabalaman** [OKit-Scripts-Projects/DSM.Customizations#3]
Hi,
I have a DS212 with 88f6282 (armv5) x12 Series. It would be great if you can prepare compiled version for my DS212.

Do you mind to make it for me?

Thanks you very much.

**Comment by tenhow** [comment]
That's Ok, but this is the first time for armv5, you should help me test it after I uploaded.

**Comment by tenhow** [comment]
maybe they are the same

**Comment by tenhow** [comment]
@balabalaman I have compiled this, and you can test now
[link](https://github.com/OKit-Scripts-Projects/DSM.Customizations/blob/master/App.Debian-Chroot.md)

**Comment by tenhow** [comment]
@balabalaman as there is no feedback, I will close this issue.

**Comment by balabalaman** [comment]
I am sorry, I lost my password to login back to here. It took me few days to find it back. Anyways, thanks for the hard work. I shall tried it later on.

**Comment by tenhow** [comment]
you can try and commit your result here after you have tried.

**Comment by balabalaman** [comment]
mate, thx a lot
