### ISSUE TITLE
Build for DS216j (Armada38x)

### ISSUE THREAD

**Issue by d4n1elchen** [OKit-Scripts-Projects/DSM.Customizations#4]
Hi, could you build Armada38x version for my DS216j? Thanks!

**Comment by tenhow** [comment]
compiling

**Comment by tenhow** [comment]
@d4n1elchen done. you can download and test now. If there is any problem, commit here.

**Comment by tenhow** [comment]
@d4n1elchen as there is no new feedback, I will close this issue.
