### ISSUE TITLE
Worked awesome, but have some more questions.

### ISSUE THREAD

**Issue by markedphillips** [OKit-Scripts-Projects/DSM.Customizations#5]
Hi, so I've installed this on a 918+ and figuring out where to autostart this is confusing for me. Is there plans to get the GUI in the synology/interface working again?

**Comment by paul-xor** [comment]
Hi, 
I am using synology_armada375_ds215j.
Could you kindly add .spk for this platform?

Many thanks.

**Comment by tenhow** [comment]
@paul-xor :),I'll do it tonight.

**Comment by tenhow** [comment]
@markedphillips the debian service gui seems available. you could try. If I have time I'll test it. If no available, I'll give you shell solution.

**Comment by tenhow** [comment]
@paul-xor compiling.

**Comment by tenhow** [comment]
@paul-xor 
[Tenhow.debian-chroot.dsm6.[1/2].armada375](https://www.dropbox.com/s/6oc6ioc2c7abqti/tenhow.debian-chroot.dsm6.%5B1%3A2%5D.rtd1296.zip?dl=0) [as DS215j]
You can test it now.

**Comment by tenhow** [comment]
As there is no feedback, I'll close it.
