### ISSUE TITLE
DS216Play request

### ISSUE THREAD

**Issue by terlanks** [OKit-Scripts-Projects/DSM.Customizations#6]
Hi 
I have a DS216play with STM STiH412.
Is this mode available to compile a new one?
Really appreciate to konw this repository that is really nice.

Thank you so much.

**Comment by tenhow** [comment]
Sorry for a long time leaving, I'll try it tonight.

**Comment by tenhow** [comment]
@terlanks Actually, your model's arch is Monaco.

**Comment by tenhow** [comment]
compiling

**Comment by tenhow** [comment]
[Tenhow.debian-chroot.dsm6.[1/2].monaco](https://www.dropbox.com/s/3a6ocgfvdshzixr/tenhow.debian-chroot.dsm6.%5B1%3A2%5D.monaco.zip?dl=0) [as DS216play]
You can test it now.

**Comment by tenhow** [comment]
As there is no feedback, I'll close it.
