### ISSUE TITLE
Build for DS218 (rtd1296)

### ISSUE THREAD

**Issue by gypittmann** [OKit-Scripts-Projects/DSM.Customizations#7]
Could you please create a build for rtd1296 CPU?

Thank you very much!

**Comment by tenhow** [comment]
Sorry for a long time leaving, I'll try it tonight.

**Comment by tenhow** [comment]
compiling

**Comment by tenhow** [comment]
I've googled rtd1296 and found that it's cpu is cortex-a53, and it's architecture is ARMv8-A 64-bit. So I try to compile one with armhf architecture.

**Comment by tenhow** [comment]
[Tenhow.debian-chroot.dsm6.[1/2].rtd1296](https://www.dropbox.com/s/6oc6ioc2c7abqti/tenhow.debian-chroot.dsm6.%5B1%3A2%5D.rtd1296.zip?dl=0) [as DS418] 
What a pitty for this.But I would like to commit it here :). If you have any other need int the future, just tell me. Merry Christmas！

**Comment by tenhow** [comment]
As there is no feedback, I'll close it.
