### ISSUE TITLE
DS415 Request

### ISSUE THREAD

**Issue by rasmusmaagaard** [OKit-Scripts-Projects/DSM.Customizations#8]
Hi,

Is it possible to build and install this on a Synology DS415 (Intel Atom CE5335, Dual Core, Evansport, 1 GB)?

Thank you very much :)

/rasmus

**Comment by g91720** [comment]
Second that.

Same CPU Synology DS214 Play (Intel Atom CE5335, Dual Core, Evansport, 1 GB)

Thank you so much.

**Comment by tenhow** [comment]
https://www.dropbox.com/s/2cmi66fp0mst949/tenhow.debian-chroot.dsm6.%5B1%20or%202%5D.evansport.zip?dl=0

**Comment by g91720** [comment]
Thank you so much ! 
you are the man

**Comment by tenhow** [comment]
Thanks, you are welcome

**Comment by rasmusmaagaard** [comment]
Looking forward to use it. Thank you 👍
