### ISSUE TITLE
build for Broadwell  (DS3617xs) thx  

### ISSUE THREAD

**Issue by p2o5** [OKit-Scripts-Projects/DSM.Customizations#9]
build for Broadwell  (DS3617xs) thx

**Comment by p2o5** [comment]
build "debian chroot" for Broadwell (DS3617xs). thx

**Comment by p2o5** [comment]
build "debian chroot" for Broadwell (DS3617xs). thx

**Comment by p2o5** [comment]
Thx!According to your article,i'd built "debian chroot" for broadwell(DS3617xs).

**Comment by tenhow** [comment]
Nice job!

**Comment by tenhow** [comment]
Actually, this package has existed in my repo for a long time.

https://www.dropbox.com/s/trav40yk89sghgc/tenhow.debian-chroot.dsm6.%5B1%20or%202%5D.braswell.zip?dl=0
